from typing import List, Tuple

def make_bbox_larger(coordinates: Tuple[int, int, int, int], percentage: float) -> Tuple[float, float, float, float]: ...
def clip_detections(detections: List[Tuple[int, int, int, int]], image_shape) -> List[Tuple[int, int, int, int]]: ...
