import numpy as np
from _typeshed import Incomplete
from typing import List, Tuple

class Googlifier:
    face_detector: Incomplete
    eyes_detector: Incomplete
    logger: Incomplete
    def __init__(self, config_file_path: str) -> None: ...
    def detect_eyes_and_googlify(self, image_byte_array: bytes) -> Tuple[bool, bytes]: ...
    def detect_faces(self, image: np.ndarray) -> List[Tuple[int, int, int, int]]: ...
    def detect_eyes(self, image: np.ndarray, faces: List[Tuple[int, int, int, int]]) -> List[Tuple[int, int, int, int]]: ...
