import numpy as np
from typing import List, Tuple

def draw_googly_eyes_on_image(eyes: List[Tuple[int, int, int, int]], image: np.ndarray) -> np.ndarray: ...
def convert_image_to_bytes(image_cv: np.ndarray) -> bytes: ...
def convert_bytes_to_image(image_byte_array: bytes) -> np.ndarray: ...
